[2025-02-14T13:36:06.847+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:36:06.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:36:07.246+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:36:07.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:36:09.604+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:36:08.882+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:36:09.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:36:10.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 6.545 seconds
[2025-02-14T13:36:41.731+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:36:41.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:36:41.843+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:36:41.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:36:42.045+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:36:42.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:36:42.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:36:42.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.752 seconds
[2025-02-14T13:37:12.873+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:37:12.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:37:12.884+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:37:12.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:37:12.926+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:37:12.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:37:12.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:37:12.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.116 seconds
[2025-02-14T13:37:43.351+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:37:43.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:37:43.357+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:37:43.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:37:43.383+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:37:43.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:37:43.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:37:43.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.105 seconds
[2025-02-14T13:38:14.110+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:38:14.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:38:14.115+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:38:14.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:38:14.146+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:38:14.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:38:14.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:38:14.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.120 seconds
[2025-02-14T13:38:44.675+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:38:44.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:38:44.686+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:38:44.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:38:44.713+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:38:44.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:38:44.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:38:44.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.211 seconds
[2025-02-14T13:39:15.213+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:39:15.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:39:15.223+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:39:15.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:39:15.250+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:39:15.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:39:15.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:39:15.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.107 seconds
[2025-02-14T13:39:45.599+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:39:45.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:39:45.605+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:39:45.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:39:45.635+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:39:45.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:39:45.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:39:45.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.093 seconds
[2025-02-14T13:40:15.958+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:40:15.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:40:15.964+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:40:15.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:40:15.988+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:40:15.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:40:15.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:40:16.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.081 seconds
[2025-02-14T13:40:46.457+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:40:46.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:40:46.463+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:40:46.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:40:46.500+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:40:46.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:40:46.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:40:46.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.106 seconds
[2025-02-14T13:41:16.777+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:41:16.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:41:16.782+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:41:16.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:41:16.805+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:41:16.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:41:16.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:41:16.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.082 seconds
[2025-02-14T13:41:47.194+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:41:47.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:41:47.203+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:41:47.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:41:47.385+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:41:47.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:41:47.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:41:47.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.284 seconds
[2025-02-14T13:42:17.844+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:42:17.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:42:17.868+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:42:17.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:42:17.910+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:42:17.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:42:17.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:42:17.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.160 seconds
[2025-02-14T13:42:48.166+0000] {processor.py:186} INFO - Started process (PID=479) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:42:48.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:42:48.173+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:42:48.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:42:48.205+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:42:48.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:42:48.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:42:48.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.111 seconds
[2025-02-14T13:43:18.718+0000] {processor.py:186} INFO - Started process (PID=504) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:43:18.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:43:18.724+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:43:18.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:43:18.768+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:43:18.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:43:18.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:43:18.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.216 seconds
[2025-02-14T13:43:49.076+0000] {processor.py:186} INFO - Started process (PID=529) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:43:49.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:43:49.085+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:43:49.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:43:49.153+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:43:49.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:43:49.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:43:49.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.176 seconds
[2025-02-14T13:44:19.879+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:44:19.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:44:19.886+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:44:19.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:44:19.933+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:44:19.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:44:19.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:44:20.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.134 seconds
[2025-02-14T13:44:50.094+0000] {processor.py:186} INFO - Started process (PID=579) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:44:50.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:44:50.100+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:44:50.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:44:50.141+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:44:50.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:44:50.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:44:50.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.104 seconds
[2025-02-14T13:45:20.598+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:45:20.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:45:20.612+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:45:20.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:45:20.660+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:45:20.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:45:20.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:45:20.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.144 seconds
[2025-02-14T13:45:51.287+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:45:51.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:45:51.293+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:45:51.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:45:51.332+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:45:51.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:45:51.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:45:51.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.099 seconds
[2025-02-14T13:46:22.122+0000] {processor.py:186} INFO - Started process (PID=654) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:46:22.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:46:22.149+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:46:22.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:46:22.243+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:46:22.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:46:22.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:46:22.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.256 seconds
[2025-02-14T13:46:52.881+0000] {processor.py:186} INFO - Started process (PID=679) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:46:52.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:46:52.896+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:46:52.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:46:52.977+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:46:52.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:46:52.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:46:53.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.182 seconds
[2025-02-14T13:47:23.957+0000] {processor.py:186} INFO - Started process (PID=704) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:47:23.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:47:23.964+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:47:23.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:47:24.000+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:47:23.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:47:24.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:47:24.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.098 seconds
[2025-02-14T13:47:54.644+0000] {processor.py:186} INFO - Started process (PID=729) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:47:54.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:47:54.662+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:47:54.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:47:54.757+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:47:54.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:47:54.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:47:54.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.194 seconds
[2025-02-14T13:48:24.995+0000] {processor.py:186} INFO - Started process (PID=754) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:48:24.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:48:25.002+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:48:25.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:48:25.036+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:48:25.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:48:25.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:48:25.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.094 seconds
[2025-02-14T13:48:55.351+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:48:55.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:48:55.358+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:48:55.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:48:55.396+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:48:55.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:48:55.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:48:55.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.098 seconds
[2025-02-14T13:49:25.794+0000] {processor.py:186} INFO - Started process (PID=804) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:49:25.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:49:25.803+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:49:25.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:49:25.869+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:49:25.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:49:25.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:49:25.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.219 seconds
[2025-02-14T13:49:56.754+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:49:56.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:49:56.770+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:49:56.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:49:56.832+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:49:56.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:49:56.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:49:56.919+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.191 seconds
[2025-02-14T13:50:27.888+0000] {processor.py:186} INFO - Started process (PID=854) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:50:27.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:50:27.896+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:50:27.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:50:27.930+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:50:27.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:50:27.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:50:27.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.101 seconds
[2025-02-14T13:50:58.223+0000] {processor.py:186} INFO - Started process (PID=879) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:50:58.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:50:58.230+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:50:58.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:50:58.266+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:50:58.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:50:58.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:50:58.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.097 seconds
[2025-02-14T13:51:28.985+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:51:28.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:51:28.990+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:51:28.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:51:29.021+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:51:29.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:51:29.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:51:29.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.100 seconds
[2025-02-14T13:51:59.665+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:51:59.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:51:59.673+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:51:59.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:51:59.712+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:51:59.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:51:59.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:51:59.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.102 seconds
[2025-02-14T13:52:30.325+0000] {processor.py:186} INFO - Started process (PID=977) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:52:30.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:52:30.332+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:52:30.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:52:30.369+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:52:30.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:52:30.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:52:30.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.100 seconds
[2025-02-14T13:53:01.246+0000] {processor.py:186} INFO - Started process (PID=1002) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:53:01.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:53:01.254+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:53:01.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:53:01.287+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:53:01.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:53:01.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:53:01.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.120 seconds
[2025-02-14T13:53:32.168+0000] {processor.py:186} INFO - Started process (PID=1027) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:53:32.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:53:32.177+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:53:32.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:53:32.229+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:53:32.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:53:32.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:53:32.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.150 seconds
[2025-02-14T13:54:03.259+0000] {processor.py:186} INFO - Started process (PID=1052) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:54:03.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:54:03.265+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:54:03.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:54:03.297+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:54:03.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:54:03.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:54:03.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.086 seconds
[2025-02-14T13:54:34.057+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:54:34.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:54:34.062+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:54:34.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:54:34.098+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:54:34.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:54:34.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:54:34.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.112 seconds
[2025-02-14T13:55:04.974+0000] {processor.py:186} INFO - Started process (PID=1102) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:55:04.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:55:04.980+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:55:04.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:55:05.013+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:55:05.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:55:05.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:55:05.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.091 seconds
[2025-02-14T13:55:36.581+0000] {processor.py:186} INFO - Started process (PID=1182) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:55:36.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:55:36.586+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:55:36.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:55:36.642+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:55:36.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:55:36.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:55:36.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.165 seconds
[2025-02-14T13:56:07.621+0000] {processor.py:186} INFO - Started process (PID=1222) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:56:07.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:56:07.627+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:56:07.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:56:07.665+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:56:07.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:56:07.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:56:07.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.119 seconds
[2025-02-14T13:56:37.903+0000] {processor.py:186} INFO - Started process (PID=1262) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:56:37.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:56:38.173+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:56:38.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:56:38.376+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:56:38.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:56:38.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:56:38.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.633 seconds
[2025-02-14T13:57:08.840+0000] {processor.py:186} INFO - Started process (PID=1287) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:57:08.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:57:08.848+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:57:08.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:57:08.886+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:57:08.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:57:08.887+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:57:08.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.135 seconds
[2025-02-14T13:57:39.336+0000] {processor.py:186} INFO - Started process (PID=1312) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:57:39.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:57:39.341+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:57:39.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:57:39.377+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:57:39.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:57:39.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:57:39.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.101 seconds
[2025-02-14T13:58:09.533+0000] {processor.py:186} INFO - Started process (PID=1342) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:58:09.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:58:09.539+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:58:09.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:58:09.572+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:58:09.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:58:09.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:58:09.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.103 seconds
[2025-02-14T13:58:39.971+0000] {processor.py:186} INFO - Started process (PID=1365) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:58:39.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:58:39.977+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:58:39.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:58:40.047+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:58:40.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:58:40.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:58:40.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.420 seconds
[2025-02-14T13:59:11.143+0000] {processor.py:186} INFO - Started process (PID=1390) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:59:11.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:59:11.149+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:59:11.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:59:11.184+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:59:11.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:59:11.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:59:11.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.114 seconds
[2025-02-14T13:59:42.063+0000] {processor.py:186} INFO - Started process (PID=1415) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T13:59:42.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T13:59:42.076+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:59:42.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T13:59:42.124+0000] {logging_mixin.py:190} INFO - [2025-02-14T13:59:42.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T13:59:42.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T13:59:42.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.164 seconds
[2025-02-14T14:00:13.281+0000] {processor.py:186} INFO - Started process (PID=1440) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:00:13.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:00:13.298+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:00:13.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:00:13.385+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:00:13.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:00:13.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:00:13.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.253 seconds
[2025-02-14T14:00:43.911+0000] {processor.py:186} INFO - Started process (PID=1465) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:00:43.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:00:43.919+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:00:43.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:00:44.007+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:00:43.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:00:44.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:00:44.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.368 seconds
[2025-02-14T14:01:15.101+0000] {processor.py:186} INFO - Started process (PID=1490) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:01:15.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:01:15.108+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:01:15.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:01:15.152+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:01:15.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:01:15.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:01:15.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.120 seconds
[2025-02-14T14:01:50.726+0000] {processor.py:186} INFO - Started process (PID=1515) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:01:50.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:01:50.730+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:01:50.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:01:50.773+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:01:50.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:01:50.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:01:50.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.178 seconds
[2025-02-14T14:02:21.809+0000] {processor.py:186} INFO - Started process (PID=1542) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:02:21.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:02:21.821+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:02:21.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:02:21.877+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:02:21.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:02:21.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:02:22.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.281 seconds
[2025-02-14T14:02:52.369+0000] {processor.py:186} INFO - Started process (PID=1565) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:02:52.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:02:52.384+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:02:52.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:02:52.450+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:02:52.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:02:52.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:02:52.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.283 seconds
[2025-02-14T14:03:23.433+0000] {processor.py:186} INFO - Started process (PID=1612) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:03:23.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:03:23.439+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:03:23.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:03:23.467+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:03:23.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:03:23.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:03:23.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.090 seconds
[2025-02-14T14:03:56.889+0000] {processor.py:186} INFO - Started process (PID=1637) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:03:56.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:03:56.901+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:03:56.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:03:57.579+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:03:57.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:03:57.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:03:57.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 0.865 seconds
[2025-02-14T14:04:31.511+0000] {processor.py:186} INFO - Started process (PID=1662) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:04:31.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:04:31.580+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:04:31.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:04:33.189+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:04:32.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:04:33.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:04:33.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 1.862 seconds
[2025-02-14T14:04:38.551+0000] {processor.py:186} INFO - Started process (PID=1672) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:04:38.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:04:38.614+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:04:38.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:04:39.629+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:04:39.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:04:39.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:04:39.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 1.277 seconds
[2025-02-14T14:05:14.630+0000] {processor.py:186} INFO - Started process (PID=1695) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:05:14.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:05:14.665+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:05:14.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:05:16.436+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:05:15.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:05:16.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:05:16.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 2.064 seconds
[2025-02-14T14:05:49.158+0000] {processor.py:186} INFO - Started process (PID=1720) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:05:49.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:05:49.607+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:05:49.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:05:54.938+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:05:54.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:05:54.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:05:56.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 6.840 seconds
[2025-02-14T14:06:36.639+0000] {processor.py:186} INFO - Started process (PID=1747) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:06:36.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:06:36.645+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:06:36.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:06:37.795+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:06:37.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:06:37.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:06:39.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 2.721 seconds
[2025-02-14T14:07:12.169+0000] {processor.py:186} INFO - Started process (PID=1772) to work on /opt/airflow/dags/tes dag.py
[2025-02-14T14:07:12.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/tes dag.py for tasks to queue
[2025-02-14T14:07:12.589+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:07:12.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/tes dag.py
[2025-02-14T14:07:14.347+0000] {logging_mixin.py:190} INFO - [2025-02-14T14:07:14.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/tes dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/tes dag.py", line 47, in <module>
    task_module = load_external_script(script_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tes dag.py", line 20, in load_external_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1132, in get_code
  File "<frozen importlib._bootstrap_external>", line 1190, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/task_hello.py'
[2025-02-14T14:07:14.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/tes dag.py
[2025-02-14T14:07:16.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/tes dag.py took 4.924 seconds
